"""Analyze extraction artifacts to guide schema and quality decisions."""

from __future__ import annotations

import argparse
from collections import Counter
import json
from pathlib import Path
import sys

PROJECT_ROOT = Path(__file__).resolve().parents[1]


def parse_args() -> argparse.Namespace:
    """Parse input summary and output analysis paths."""

    parser = argparse.ArgumentParser(
        description="Analyze extracted JSON files from a batch run."
    )
    parser.add_argument(
        "--summary",
        type=Path,
        default=PROJECT_ROOT / "outputs" / "reports" / "batch_summary_50.json",
        help="Batch summary JSON generated by scripts/run_batch_pdfs.py.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=PROJECT_ROOT / "outputs" / "reports" / "extraction_analysis_50.json",
        help="Path for the analysis report JSON.",
    )
    return parser.parse_args()


def load_json(path: Path) -> dict:
    """Load JSON and tolerate old files with trailing null bytes."""

    return json.loads(path.read_bytes().rstrip(b"\x00").decode("utf-8"))


def resolve_project_path(path_value: str) -> Path:
    """Resolve relative paths and older absolute WSL paths from summaries."""

    path = Path(path_value)
    if path.exists():
        return path
    candidate = PROJECT_ROOT / path_value
    if candidate.exists():
        return candidate

    normalized = path_value.replace("\\", "/")
    marker = f"/{PROJECT_ROOT.name}/"
    if marker in normalized:
        candidate = PROJECT_ROOT / normalized.split(marker, 1)[1]
        if candidate.exists():
            return candidate
    return path


def missing_counts(items: list[dict], prefix: str) -> dict[str, dict[str, int]]:
    """Calculate present/missing counts for each field in a list of objects."""

    field_counts: Counter[str] = Counter()
    missing: Counter[str] = Counter()
    for item in items:
        for key, value in item.items():
            full_key = f"{prefix}.{key}"
            field_counts[full_key] += 1
            if value in (None, "", []):
                missing[full_key] += 1

    return {
        key: {
            "missing": missing[key],
            "total": total,
            "present": total - missing[key],
        }
        for key, total in sorted(field_counts.items())
    }


def stringify_counter(counter: Counter) -> dict[str, int]:
    """Convert Counter keys to JSON-safe strings."""

    return {
        "null" if key is None else str(key): value
        for key, value in counter.items()
    }


def main() -> int:
    """Read batch outputs and write an aggregate data-quality report."""

    args = parse_args()
    summary_path = args.summary.resolve()
    if not summary_path.exists():
        print(f"Summary not found: {summary_path}", file=sys.stderr)
        return 1

    summary = load_json(summary_path)
    results = summary.get("results", [])

    deed_counts = Counter()
    page_counts = Counter()
    source_types = Counter()
    languages = Counter()
    party_types = Counter()
    deed_types = Counter()
    companies: list[dict] = []
    parties: list[dict] = []
    publication_reference_count = 0
    form_reference_count = 0
    enterprise_number_count = 0

    for result in results:
        if not result.get("success"):
            continue

        # Summary-level counts show batch behavior before reading each JSON artifact.
        deed_counts[result.get("deeds_extracted")] += 1
        page_counts[result.get("page_count")] += 1
        extraction_path = resolve_project_path(result["gemini_json_path"])
        if not extraction_path.exists():
            continue

        document = load_json(extraction_path)
        source_types[document.get("source_type")] += 1
        for deed in document.get("deeds", []):
            # Deed/company/party counters expose normalization and completeness gaps.
            languages[deed.get("language")] += 1
            deed_types[deed.get("deed_type")] += 1
            if deed.get("publication_reference"):
                publication_reference_count += 1
            if deed.get("form_reference"):
                form_reference_count += 1
            for company in deed.get("companies", []):
                companies.append(company)
                if company.get("enterprise_number"):
                    enterprise_number_count += 1
            for party in deed.get("party_roles", []):
                parties.append(party)
                party_types[party.get("party_type")] += 1

    analysis = {
        "batch_summary": {
            key: value for key, value in summary.items() if key != "results"
        },
        "deeds_per_pdf": stringify_counter(Counter(dict(sorted(deed_counts.items())))),
        "pages_per_pdf": stringify_counter(Counter(dict(sorted(page_counts.items())))),
        "document_source_types": stringify_counter(source_types),
        "languages": stringify_counter(languages),
        "party_types": stringify_counter(party_types),
        "top_deed_types": stringify_counter(Counter(dict(deed_types.most_common(25)))),
        "reference_counts": {
            "publication_reference": publication_reference_count,
            "form_reference": form_reference_count,
        },
        "company_counts": {
            "companies": len(companies),
            "with_enterprise_number": enterprise_number_count,
        },
        "party_role_counts": {
            "party_roles": len(parties),
        },
        "company_field_completeness": missing_counts(companies, "company"),
        "party_field_completeness": missing_counts(parties, "party"),
    }

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_bytes(json.dumps(analysis, indent=2).encode("utf-8"))

    print(f"Analysis report: {args.output}")
    print(f"Deeds extracted: {summary.get('total_deeds_extracted')}")
    print(f"Companies extracted: {len(companies)}")
    print(f"Party roles extracted: {len(parties)}")
    print(f"Multi-notice PDFs: {summary.get('multi_notice_success_count')}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
